### ISSUE TITLE
Checking for user validation while signing up on backend side too.

### ISSUE THREAD

**Issue by Miran-Firdausi** [X-Evolve/Python_Hunt#52]
Assign me under hacktoberfest

**Comment by gautam-bhagat** [comment]
heyy assign me this one

**Comment by ravin-d-27** [comment]
Hello @Miran-Firdausi , could you please tell us what exactly you will be implementing here? Is it like captcha system or email validation?

**Comment by ravin-d-27** [comment]
Hello @gautam-bhagat , please check other issues as this issue will be assigned to @Miran-Firdausi soon.

**Comment by Miran-Firdausi** [comment]
Like if a user tries to signup with empty username and empty password then it resulted in an error, just that.

**Comment by ravin-d-27** [comment]
I think you have already fixed that. Since you made all the tags as `required`, it is not needed ig.
If you want to work on the issue, you can bring password validations. 
For example:
`Length`: Passwords should be at least 8 characters long. Longer passwords are generally more secure.
At least 1 `Uppercase letters (A-Z)`
At least 1 `Lowercase letters (a-z)`
At least 1 `Numbers (0-9)`
At least 1 `Special characters (e.g., !, @, #, $, %, etc.)`

I think that will be helpful.

**Comment by Miran-Firdausi** [comment]
That is on the client side. It is a good practice to add validation on server side too because if someone wants to bypass the frontend validation they can. But yes, I can work on the password validation too.

**Comment by ravin-d-27** [comment]
That's great @. Assigning this issue to you !

**Comment by ravin-d-27** [comment]
Hi @Miran-Firdausi , could you please let us know the status of your PR?

**Comment by Miran-Firdausi** [comment]
I'm Sorry I got busy in some work. I will do it today.

**Comment by ravin-d-27** [comment]
No issues @Miran-Firdausi , please take your time !
